parameters:
    locale: 'en'
    mail_from: 'microblog@test.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:
            $mailFrom: '%mail_from%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Aliases
    App\Service\MicroPost\MicroPostServiceInterface: '@App\Service\MicroPost\MySqlMicroPost'
    App\Service\Register\RegisterServiceInterface: '@App\Service\Register\MySqlRegister'
    App\Service\Mailer\MailerServiceInterface: '@App\Service\Mailer\SwiftMailer'
    App\Service\Paginator\PaginatorServiceInterface: '@App\Service\Paginator\KnpPaginator'
   
